BackendUserGroups:
  mode: "replace"
  entries:
    - { uid: 1, title: "[PAGEACCESS] Base", workspace_perms: "0" }
    - { uid: 2, title: "[FM] Base", file_mountpoints: "1", workspace_perms: "0" }
    - { uid: 3, title: "[DBM] Base", db_mountpoints: "1", workspace_perms: "0" }
    - { uid: 5, title: "[ROLE] Site Administrator:innen", subgroup: "1,3,2", workspace_perms: "1", permission_sets: "itzbund/gsb-core/acl-site-admin" }
    - { uid: 7, title: "[ROLE] Chefredakteur:innen", subgroup: "1,2", permission_sets: "itzbund/gsb-core/acl-editor-in-chief", workspace_perms: "0" }
    - { uid: 9, title: "[ROLE] Redakteur:innen", subgroup: "1,2", permission_sets: "itzbund/gsb-core/acl-editor", workspace_perms: "0" }
