# SPDX-FileCopyrightText: 2024 Bundesrepublik Deutschland, vertreten durch das BMI/ITZBund
#
# SPDX-License-Identifier: GPL-3.0-or-later

BackendUserGroups:
  mode: "update"
  entries:
    - {
        uid: 1,
        title: "[GSB][DBM] Base",
        non_exclude_fields: "",
        explicit_allowdeny: "",
        allowed_languages: "",
        db_mountpoints: "",
        file_mountpoints: "",
        file_permissions: "",
        workspace_perms: "0",
        category_perms: "0",
        permission_sets: "itzbund/gsb-core/acl-dbm-base",
      }
    - {
        uid: 3,
        title: "[GSB][FM] Base",
        non_exclude_fields: "",
        explicit_allowdeny: "",
        allowed_languages: "",
        db_mountpoints: "",
        file_mountpoints: "1",
        file_permissions: "",
        workspace_perms: "0",
        category_perms: "0",
        permission_sets: "itzbund/gsb-core/acl-fm-base",
      }
    - {
        uid: 4,
        title: "[GSB][PAGEACCESS] Base",
        non_exclude_fields: "",
        explicit_allowdeny: "",
        allowed_languages: "",
        db_mountpoints: "",
        file_mountpoints: "",
        file_permissions: "",
        workspace_perms: "0",
        category_perms: "0",
        permission_sets: "",
      }
    - {
        uid: 5,
        title: "[GSB][ROLE] Chefredaktion",
        non_exclude_fields: "",
        explicit_allowdeny: "",
        allowed_languages: "",
        db_mountpoints: "",
        file_mountpoints: "",
        file_permissions: "",
        workspace_perms: "1",
        category_perms: "0",
        permission_sets: "itzbund/gsb-core/acl-chef-redaktion",
        TSconfig: "@import 'EXT:gsb_core/Configuration/TsConfig/User/Editor.tsconfig'",
        subgroup: "4,9,1,6",
      }
    - {
        uid: 6,
        title: "[GSB][ROLE] Redaktion",
        non_exclude_fields: "",
        explicit_allowdeny: "",
        allowed_languages: "",
        db_mountpoints: "",
        file_mountpoints: "",
        file_permissions: "",
        workspace_perms: "0",
        category_perms: "0",
        permission_sets: "itzbund/gsb-core/acl-redaktion",
        TSconfig: "@import 'EXT:gsb_core/Configuration/TsConfig/User/Editor.tsconfig'",
        subgroup: "4,13,1",
      }
    - {
        uid: 7,
        title: "[GSB][ROLE] Site Adminstrator:innen",
        non_exclude_fields: "",
        explicit_allowdeny: "",
        allowed_languages: "",
        db_mountpoints: "",
        file_mountpoints: "",
        file_permissions: "",
        workspace_perms: "1",
        category_perms: "0",
        permission_sets: "",
        TSconfig: "@import 'EXT:gsb_core/Configuration/TsConfig/User/SiteAdmin.tsconfig'",
      }
    - {
        uid: 8,
        title: "[GSB][ROLE] System Adminstrator:innen",
        non_exclude_fields: "",
        explicit_allowdeny: "",
        allowed_languages: "",
        db_mountpoints: "",
        file_mountpoints: "",
        file_permissions: "",
        workspace_perms: "1",
        category_perms: "0",
        permission_sets: "",
        TSconfig: "@import 'EXT:gsb_core/Configuration/TsConfig/User/SystemAdmin.tsconfig'",
      }
    - {
        uid: 9,
        title: "[GSB][FM] Base - NO Delete",
        non_exclude_fields: "",
        explicit_allowdeny: "",
        allowed_languages: "",
        db_mountpoints: "",
        file_mountpoints: "1",
        file_permissions: "",
        workspace_perms: "0",
        category_perms: "0",
        permission_sets: "itzbund/gsb-core/acl-fm-base-no-delete",
      }
    - {
        uid: 10,
        title: "[GSB][ROLE] Selbständige Redaktion",
        non_exclude_fields: "",
        explicit_allowdeny: "",
        allowed_languages: "",
        db_mountpoints: "",
        file_mountpoints: "",
        file_permissions: "",
        workspace_perms: "1",
        category_perms: "0",
        permission_sets: "itzbund/gsb-core/acl-redaktion-live",
        TSconfig: "@import 'EXT:gsb_core/Configuration/TsConfig/User/Editor.tsconfig'",
        subgroup: "6",
      }
    - {
        uid: 11,
        title: "[GSB][EXTEND] Externer Zugriff",
        non_exclude_fields: "",
        explicit_allowdeny: "",
        allowed_languages: "",
        db_mountpoints: "",
        file_mountpoints: "",
        file_permissions: "",
        workspace_perms: "0",
        category_perms: "0",
        permission_sets: "",
        TSconfig: "@import 'EXT:gsb_core/Configuration/TsConfig/User/ForceMFA.tsconfig'",
      }
    - {
        uid: 12,
        title: "[GSB][ROLE] Website User Admin",
        non_exclude_fields: "",
        explicit_allowdeny: "",
        allowed_languages: "",
        db_mountpoints: "",
        file_mountpoints: "",
        file_permissions: "",
        workspace_perms: "0",
        category_perms: "0",
        permission_sets: "itzbund/gsb-core/acl-website-user-admin",
        subgroup: "9,1,4",
        TSconfig: "@import 'EXT:gsb_core/Configuration/TsConfig/User/FrontendUserAdmin.tsconfig'",
      }
    - {
        uid: 13,
        title: "[GSB][FM] Base - Minimal",
        non_exclude_fields: "",
        explicit_allowdeny: "",
        allowed_languages: "",
        db_mountpoints: "",
        file_mountpoints: "1",
        file_permissions: "",
        workspace_perms: "0",
        category_perms: "0",
        permission_sets: "itzbund/gsb-core/acl-fm-minimal",
      }
