---
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: 'conventionalcommits'
      releaseRules:
        - type: 'chore'
          release: 'patch'
  - - "@semantic-release/release-notes-generator"
    - preset: 'conventionalcommits'
      presetConfig:
        types:
          - type: 'feat'
            section: ':sparkles: Features'
            hidden: false
          - type: 'fix'
            section: ':bug: Fixes'
            hidden: false
          - type: 'docs'
            section: ':memo: Documentation'
            hidden: false
          - type: 'style'
            section: ':barber: Styles'
            hidden: false
          - type: 'refactor'
            section: ':zap: Refactor'
            hidden: false
          - type: 'perf'
            section: ':fast_forward: Performance'
            hidden: false
          - type: 'test'
            section: ':white_check_mark: Tests'
            hidden: false
          - type: 'ci'
            section: ':repeat: Continuous Integrations'
            hidden: false
          - type: 'chore'
            section: ':repeat: Chores'
            hidden: false
  - - "@semantic-release/gitlab"
    - gitlabUrl: https://git.gsb-itzbund.de
      assets:
        - path: gsb-core.zip
          label: GSB Core (zip)
          type: package
        - path: Documentation/Release.md
          label: Release Notes
        - path: phpmetrics/*
          label: php Metriken
        - url: https://git.gsb-itzbund.de/gsb11/extensions/gsb_core/-/blob/main/README.md
          label: README
branches:
  - name: release
  - name: main
    prerelease: rc
