plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/gitlab"
    - gitlabUrl: https://git.gsb-itzbund.de
      assets:
        - path: gsb-distribution.zip
          label: GSB Distribution (zip)
          target: generic_package
        - path: Documentation/Release.md
          label: Release Notes
          target: generic_package
        - url: https://git.gsb-itzbund.de/gsb11/distribution-package-gsb_template/-/blob/main/README.md
          label: README
          target: generic_package
branches:
  - name: release
  - name: main
    prerelease: rc
