plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/gitlab"
    - gitlabUrl: https://git.gsb-itzbund.de
      assets:
        - path: gsb-core.zip
          label: GSB Core (zip)
          type: package
        - path: Documentation/Release.md
          label: Release Notes
        - path: phpmetrics/*
          label: php Metriken
        - url: https://git.gsb-itzbund.de/gsb11/extensions/gsb_core/-/blob/main/README.md
          label: README
branches:
  - name: release
  - name: main
    prerelease: rc
