<?php

namespace ITZBund\GsbCore\Xclass;

use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Install\CoreVersion\MaintenanceWindow;

class CoreVersionService extends \TYPO3\CMS\Install\Service\CoreVersionService
{
    public function getMaintenanceWindow(): \TYPO3\CMS\Install\CoreVersion\MaintenanceWindow
    {
        return parent::getMaintenanceWindow(); // TODO: Change the autogenerated stub
    }

    public function getSupportedMajorReleases(): array
    {
        return parent::getSupportedMajorReleases(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \TYPO3\CMS\Install\Service\Exception\RemoteFetchException
     */
    protected function fetchFromRemote(string $url): array
    {
        return parent::fetchFromRemote($url);
    }

    private function isOfflineMode(): bool
    {
        return $GLOBALS['TYPO3_CONF_VARS']['offlineMode'];
    }
}
