<?php

namespace ITZBund\GsbCore\Xclass;

use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Install\CoreVersion\MaintenanceWindow;

class CoreVersionService extends \TYPO3\CMS\Install\Service\CoreVersionService
{
    public function getMaintenanceWindow(): \TYPO3\CMS\Install\CoreVersion\MaintenanceWindow
    {
        die('fooo');
        if ($this->isOfflineMode()) {
            $response = [
                'maintained_until' => 00,
            'elts_until' => 00,
            ];
            return MaintenanceWindow::fromApiResponse($response);
        }
        return parent::getMaintenanceWindow(); // TODO: Change the autogenerated stub
    }

    public function getSupportedMajorReleases(): array
    {
        return parent::getSupportedMajorReleases(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \TYPO3\CMS\Install\Service\Exception\RemoteFetchException
     */
    protected function fetchFromRemote(string $url): array
    {
        die('bar');
        $url = $this->apiBaseUrl . $url;
        $json = GeneralUtility::getUrl($url);

        if (!$json) {
            $this->throwFetchException($url);
        }
        return json_decode($json, true);
    }

    private function isOfflineMode()
    {
        return $GLOBALS['TYPO3_CONF_VARS']['offlineMode'];
    }
}
