settings:
  copyright.notice:
    category: GSB.copyrightCategory
    type: string
    default: 'ITZBund'

  copyright.show-copyright:
    type: bool
    default: false
    category: GSB.copyrightCategory
