categories:
  GSB.copyrightCategory:
    label: 'Copyright (Urheberrechtshinweis) Einstellungen'
    parent: GSB
settings:
  copyright.notice:
    label: 'Urheberrechtshinweis '
    category: GSB.copyrightCategory
    description: 'Der Urheberrechtshinweis wird im Footer mit der aktuellen Jahreszahl ausgespielt.'
    type: string
    default: 'meine Behörde'

  copyright.show-copyright:
    type: bool
    default: false
    category: GSB.copyrightCategory
    label: 'Copyright anzeigen'
    description: 'Copyright auch an Teaser oder Bühnen-Bildern anzeigen.'

 