categories:
  GSB:
    label: 'GSB Individualisierungs Einstellungen'
  GSB.functions:
    label: 'Funktionen Einstellungen'
    parent: GSB
  GSB.functions.categories:
    label: 'Kategorien Einstellungen'
    parent: GSB.functions
  GSB.functions.socialMediaLinks:
    label: 'Social Media Links Einstellungen'
    parent: GSB.functions
  GSB.functions.suche:
    label: 'Suche Einstellungen'
    parent: GSB.functions
  GSB.functions.navigation:
    label: 'Navigation Einstellungen'
    parent: GSB.functions
  GSB.functions.accessability:
    label: 'Barrierefreiheit Einstellungen'
    parent: GSB.functions

settings:


### Navigation Einstellungen ###
  navigation.gsb-navType:
    type: string
    default: '0'
    category: GSB.functions.navigation
    label: 'Navigations-Typ'
    enum:
      '0': 'Klassische Desktop Navigation'
      '1': 'Mobiles "Burger" Menü'
    description: 'Darstellungsart der Hauptnavigation in der Desktop Ansicht.'


### Social Media Links Einstellungen ###
  socialMediaLinks.x:
    label: 'X'
    category: GSB.functions.socialMediaLinks
    description: 'Links to social media profiles'
    type: string
    default: 'x.com'
  socialMediaLinks.facebook:
    label: 'Facebook'
    category: GSB.functions.socialMediaLinks
    description: 'Links to social media profiles'
    type: string
    default: 'facebook.com'
  socialMediaLinks.instagram:
    label: 'Instagram'
    category: GSB.functions.socialMediaLinks
    description: 'Links to social media profiles'
    type: string
    default: 'instagram.com'
  socialMediaLinks.xing:
    label: 'Xing'
    category: GSB.functions.socialMediaLinks
    description: 'Links to social media profiles'
    type: string
    default: 'xing.com'
  socialMediaLinks.linkedin:
    label: 'LinkedIn'
    category: GSB.functions.socialMediaLinks
    description: 'Links to social media profiles'
    type: string
    default: 'linkedin.com'
  socialMediaLinks.youtube:
    label: 'YouTube'
    category: GSB.functions.socialMediaLinks
    description: 'Links to social media profiles'
    type: string
    default: 'youtube.com'

  search.googleSiteVerification:
    label: 'Google Site Verification Code'
    category: GSB.functions
    description: 'Im diesem Feld muss der von Google Search Console bereitgestellte Verifizierungscode eingetragen werden. Dies erlaubt die Bestätigung der Eigentümerschaft der Website.'
    type: string
    default: ''

### Barrierefreiheit Einstellungen ###
  accessability.signLanguagePage:
    label: 'Gebärdensprache Seite'
    category: GSB.functions.accessability
    description: 'Konfiguration der Gebärdensprache Seite.'
    type: page
    default: 0

  accessability.simpleLanguagePage:
    label: 'Einfache Sprachen Seite'
    category: GSB.functions.accessability
    description: 'Konfiguration der Einfache Sprachen Seite.'
    type: page
    default: 0
