name: itzbund-gsb/default
label: GSB11 Standard-Set
dependencies:
  - itzbund-gsb/function
  - itzbund-gsb/copyright
  - itzbund-gsb/style
  - typo3/seo-sitemap
  - typo3/form
  - typo3/felogin
  - typo3/redirects
  - kitzberger/form-mailtext
  - typo3/fluid-styled-content
optionalDependencies:
  - itzbund-gsb/solr
  - itzbund-gsb/public-frontend
