services:
  megalinter:
    image: registry.gsb-itzbund.de/gsb11/devops/images/megalinter:1.6.15@sha256:cf7b51db01534dcd4a382661d51bd08acb72234c7a91bf5467fd3b93df3787a6
    container_name: ${PROJECT_NAME}-megalinter-container
    volumes:
      - type: bind
        source: ./../../../
        target: /var/www/html
        consistency: cached
    environment:
      DEFAULT_WORKSPACE: /var/www/html
      REPORT_OUTPUT_FOLDER: ${REPORT_OUTPUT_FOLDER}
      GIT_DEPTH: 0
      TERM: xterm-256color
      TZ: Europe/Berlin
