# Load default processing options
imports:
  - { resource: 'EXT:gsb_core/Configuration/RTE/Processing.yaml' }
  - { resource: 'EXT:gsb_core/Configuration/RTE/Editor/Base.yaml' }
  - { resource: 'EXT:gsb_core/Configuration/RTE/Editor/Plugins.yaml' }

# Add configuration for the editor
# For complete documentation see https://ckeditor.com/docs/ckeditor5/latest/features/index.html
editor:
  config:
    toolbar:
      items:
        - clipboard
        - '|'
        - undo
        - redo
        - '|'
        - style
        - heading
        # grouping separator
        - '|'
        - bold
        - italic
        - underline
        - subscript
        - superscript
        - softhyphen
        - '|'
        - bulletedList
        - numberedList
        - blockQuote
        - alignment
        - '|'
        - findAndReplace
        - link
        - '|'
        - removeFormat
        - undo
        - redo
        - '|'
        - specialCharacters
        - horizontalLine
        - sourceEditing

    heading:
      options:
        - { model: 'paragraph', title: 'Paragraph' }
        - { model: 'heading2', view: 'h2', title: 'Heading 2' }
        - { model: 'heading3', view: 'h3', title: 'Heading 3' }
        - { model: 'heading4', view: 'h4', title: 'Heading 4' }
        - { model: 'heading5', view: 'h5', title: 'Heading 5' }
        - { model: 'heading6', view: 'h6', title: 'Heading 6' }
        - { model: 'formatted', view: 'pre', title: 'Pre-Formatted Text' }

    style:
      definitions:
        - { name: "Lead", element: "p", classes: [ 'lead' ] }
        - { name: "Button Primary", element: "a", classes: [ 'btn btn-primary' ] }
        - { name: "Small", element: "small", classes: [ 'small' ] }
        - { name: "Muted", element: "span", classes: [ 'text-muted' ] }

    alignment:
      options:
        - { name: 'left', className: 'text-start' }
        - { name: 'center', className: 'text-center' }
        - { name: 'right', className: 'text-end' }
        - { name: 'justify', className: 'text-justify' }

    table:
      defaultHeadings: { rows: 1 }
      contentToolbar:
        - tableColumn
        - tableRow
        - mergeTableCells
        - tableProperties
        - tableCellProperties
