# SPDX-FileCopyrightText: 2024 Bundesrepublik Deutschland, vertreten durch das BMI/ITZBund
#
# SPDX-License-Identifier: GPL-3.0-or-later

imports:
  - {resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml"}
  - {resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml"}
  - {resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml"}

editor:
  config:
    contentsCss: ""
    debug: false
    allowedContent: true
    defaultContentLanguage: "de"
    defaultLanguage: "de"

    importModules:
      - {module: '@ckeditor/ckeditor5-language-translations.js', exports: []}
      - {module: '@ckeditor/ckeditor5-language', exports: ['TextPartLanguage']}

    heading:
      options:
        - {model: "paragraph", title: "Paragraph"}
        - {model: "heading2", view: "h2", title: "Heading 2"}
        - {model: "heading3", view: "h3", title: "Heading 3"}
        - {model: "heading4", view: "h4", title: "Heading 4"}
        - {model: "heading5", view: "h5", title: "Heading 5"}
        - {model: "heading6", view: "h6", title: "Heading 6"}

    stylesSet:
      - {name: "Paragraph: Subheader", element: "p", attributes: {'class': 'lead'}}
      - {name: "Blockquote: Quote", element: "blockquote", attributes: {'class': 'quote-dot'}}

      - {name: "Button: Primary", element: "a", attributes: {'class': 'btn btn-primary'}}
      - {name: "Button: Secondary", element: "a", attributes: {'class': 'btn btn-secondary'}}
      - {name: "Button: Tertiary", element: "a", attributes: {'class': 'btn btn-tertiary'}}

      - {name: "List ul/ol: Unstyled", element: "ul", attributes: {'class': 'list-unstyled'}}
      - {name: "List ul/ol: Inline", element: "ul", attributes: {'class': 'list-inline'}}

      - {name: "List li: Scroll", element: "li", attributes: {'class': 'list-scroll'}}

      - {name: "Link: Internal", element: "a", attributes: {'class': 'internal-link'}}
      - {name: "Link: Download", element: "a", attributes: {'class': 'download'}}
      - {name: "Link: External", element: "a", attributes: {'class': 'external-link'}}
      - {name: "Link: Email", element: "a", attributes: {'class': 'email'}}
      - {name: "Link: Phone", element: "a", attributes: {'class': 'phone'}}
      - {name: "Link: Audio", element: "a", attributes: {'class': 'audio'}}
      - {name: "Link: Video", element: "a", attributes: {'class': 'video'}}
      - {name: "Link: Glossary", element: "a", attributes: {'class': 'glossary'}}
      - {name: "Link: Public", element: "a", attributes: {'class': 'public'}}
      - {name: "Link: Legal", element: "a", attributes: {'class': 'legal'}}
      - {name: "Link: Galerie", element: "a", attributes: {'class': 'gallery'}}
      - {name: "Link: Chart", element: "a", attributes: {'class': 'chart'}}

      - {name: "Text: Kicker", element: "span", attributes: {'class': 'kicker'}}
      - {name: "Text: Lowercased", element: "span", attributes: {'class': 'text-lowercase'}}
      - {name: "Text: Uppercased", element: "span", attributes: {'class': 'text-uppercase'}}
      - {name: "Text: Capitalized", element: "span", attributes: {'class': 'text-capitalize'}}
      - {name: "Text: Bold", element: "span", attributes: {'class': 'bold'}}
      - {name: "Text: Small", element: "span", attributes: {'class': 'small'}}
      - {name: "Text: Emphasize", element: "span", attributes: {'class': 'em'}}
      - {name: "Text: Hidden", element: "span", attributes: {'class': 'hide visually-hidden'}}

      - { name: 'Headline 2 > 1', element: 'h2', attributes: {'class': 'h1'}}
      - { name: 'Headline 2 > 3', element: 'h2', attributes: {'class': 'h3'}}
      - { name: 'Headline 2 > 4', element: 'h2', attributes: {'class': 'h4'}}
      - { name: 'Headline 2 > 5', element: 'h2', attributes: {'class': 'h5'}}
      - { name: 'Headline 2 > 6', element: 'h2', attributes: {'class': 'h6'}}

      - { name: 'Headline 3 > 1', element: 'h3', attributes: {'class': 'h1'}}
      - { name: 'Headline 3 > 2', element: 'h3', attributes: {'class': 'h2'}}
      - { name: 'Headline 3 > 4', element: 'h3', attributes: {'class': 'h4'}}
      - { name: 'Headline 3 > 5', element: 'h3', attributes: {'class': 'h5'}}
      - { name: 'Headline 3 > 6', element: 'h3', attributes: {'class': 'h6'}}

      - { name: 'Headline 4 > 1', element: 'h4', attributes: {'class': 'h1'}}
      - { name: 'Headline 4 > 2', element: 'h4', attributes: {'class': 'h2'}}
      - { name: 'Headline 4 > 3', element: 'h4', attributes: {'class': 'h3'}}
      - { name: 'Headline 4 > 5', element: 'h4', attributes: {'class': 'h5'}}
      - { name: 'Headline 4 > 6', element: 'h4', attributes: {'class': 'h6'}}

      - { name: 'Headline 5 > 1', element: 'h5', attributes: {'class': 'h1'}}
      - { name: 'Headline 5 > 2', element: 'h5', attributes: {'class': 'h2'}}
      - { name: 'Headline 5 > 3', element: 'h5', attributes: {'class': 'h3'}}
      - { name: 'Headline 5 > 4', element: 'h5', attributes: {'class': 'h4'}}
      - { name: 'Headline 5 > 6', element: 'h5', attributes: {'class': 'h6'}}

      - { name: 'Headline 6 > 1', element: 'h6', attributes: {'class': 'h1'}}
      - { name: 'Headline 6 > 2', element: 'h6', attributes: {'class': 'h2'}}
      - { name: 'Headline 6 > 3', element: 'h6', attributes: {'class': 'h3'}}
      - { name: 'Headline 6 > 4', element: 'h6', attributes: {'class': 'h4'}}
      - { name: 'Headline 6 > 5', element: 'h6', attributes: {'class': 'h5'}}

    toolbar:
      items:
        - heading
        - style
        - "|"
        - textPartLanguage
        - "|"
        - bold
        - italic
        - link
        - bulletedList
        - numberedList
        - "|"
        - outdent
        - indent
        - "|"
        - blockQuote
        - alignment
        - "|"
        - undo
        - redo
        - removeFormat
        - "|"
        - insertTable
        - superscript
        - subscript
        - strikeThrough
        - horizontalLine
        - "|"
        - specialCharacters
        - sourceEditing
        - findAndReplace

    table:
      defaultHeadings: {rows: 1}
      contentToolbar:
        - tableColumn
        - tableRow
        - mergeTableCells
        - tableProperties
        - tableCellProperties
        - toggleTableCaption

    language:
      ui: "de"
      textPartLanguage:
        - {title: "Deutsch", languageCode: "de"}
        - {title: "English", languageCode: "en"}
        - {title: "Français", languageCode: "fr"}

    format_tags: "s;p;h1;h2;h3;h4;h5;h6;pre"

    processing:
      allow_tags:
        - s
        - figure
        - figcaption
        - i
        - em

    justifyClasses:
      - text-left
      - text-center
      - text-right
      - text-justify

    extraPlugins:
      - justify
      - autolink
      - showblocks
      - language

    removePlugins:
      - image

    removeButtons:
      - Underline

buttons:
  link:
    properties:
      class:
        allowedClasses: "internal-link, external-link, download, email, phone, audio, video, glossary, public, legal, gallery, chart"
