services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  ITZBund\GsbTemplate\ViewHelpers\:
    resource: '../Classes/ViewHelpers/*'
    public: true

  ITZBund\GsbTemplate\:
    resource: '../Classes/*'
    exclude: '../Classes/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  ITZBund\GsbTemplate\Command\ConfigurationImportCommand:
    tags:
      - name: console.command
        schedulable: false
        command: 'gsbtemplate:configuration:import'
        description: 'A command that does import Configuration for Workspaces and Backend User Groups from yaml-Files.'
