services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  ITZBund\GsbCore\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  ITZBund\GsbCore\Command\ConfigurationImportCommand:
    tags:
      - name: console.command
        schedulable: false
        command: 'gsbtemplate:configuration:import'
        description: 'A command that does import Configuration for Workspaces and Backend User Groups from yaml-Files.'

  ITZBund\GsbCore\Configuration\PackageHelper:
    public: true

  ITZBund\GsbCore\Configuration\ExtendSiteConfigurationRegistry:
    public: true

  ITZBund\GsbCore\Configuration\Discovery\ExtendSiteConfigurationLocator:
    public: true

  ITZBund\GsbCore\EventListener\AddTypoScriptFromSitePackageEvent:
    public: true
    arguments:
      - '@ITZBund\GsbCore\Configuration\PackageHelper'
    tags:
      - name: event.listener
        identifier: 'gsb_core/add-typoscript-from-site-package'

  ITZBund\GsbCore\EventListener\ExtendsSiteConfigurationEvent:
    public: true
    tags:
      - name: event.listener
        identifier: 'gsb_core/extends-site-configuration'

  ITZBund\GsbCore\ViewHelpers\:
    resource: '../Classes/ViewHelpers/*'
    public: true
