# SPDX-FileCopyrightText: 2024 Bundesrepublik Deutschland, vertreten durch das BMI/ITZBund
#
# SPDX-License-Identifier: GPL-3.0-or-later

services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  ITZBund\GsbCore\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'


  ITZBund\GsbCore\UserFunc\ColorPickerValueItems:
    public: true

  ITZBund\GsbCore\Configuration\PackageHelper:
    public: true

  ITZBund\GsbCore\Configuration\ExtendSiteConfigurationRegistry:
    public: true

  ITZBund\GsbCore\Configuration\Discovery\ExtendSiteConfigurationLocator:
    public: true

  ITZBund\GsbCore\DataProcessing\TargetPageDateProcessor:
    public: true

  ITZBund\GsbCore\DataProcessing\CachedMenuProcessor:
    public: true

  ITZBund\GsbCore\EventListener\AddInfoButtonToContentElementsEvent:
    public: true
    tags:
      - name: event.listener
        identifier: 'gsb_core/add-info-button-to-content-elements'

  ITZBund\GsbCore\EventListener\AddTypoScriptFromSitePackageEvent:
    public: true
    arguments:
      - '@ITZBund\GsbCore\Configuration\PackageHelper'
    tags:
      - name: event.listener
        identifier: 'gsb_core/add-typoscript-from-site-package'

  ITZBund\GsbCore\EventListener\ExtendsSiteConfigurationEvent:
    public: true
    tags:
      - name: event.listener
        identifier: 'gsb_core/extends-site-configuration'

  ITZBund\GsbCore\EventListener\SynchronizeLocalizedSiteSettings:
    public: true
    tags:
      - name: event.listener
        identifier: 'gsb_core/synchronize-localized-site-settings'

  ITZBund\GsbCore\EventListener\BackendFormValidUrlListener:
    tags:
      - name: signal
        identifier: TYPO3\CMS\Backend\Form\FormDataProvider\TcaDatabaseRecord->getDataPostProc

  ITZBund\GsbCore\ViewHelpers\:
    resource: '../Classes/ViewHelpers/*'
    public: true

  ITZBund\GsbCore\Controller\ReportController:
    tags: ['backend.controller']
