# SPDX-FileCopyrightText: 2024 Bundesrepublik Deutschland, vertreten durch das BMI/ITZBund
#
# SPDX-License-Identifier: GPL-3.0-or-later

services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  ITZBund\GsbCore\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  ITZBund\GsbCore\Command\ConfigurationImportCommand:
    tags:
      - name: console.command
        schedulable: false
        command: 'gsbcore:configuration:import'
        description: 'A command that does import Configuration for Workspaces and Backend User Groups from yaml-Files.'

  ITZBund\GsbCore\Command\TriggerSynchronizeConfigurationCommand:
    tags:
      - name: console.command
        schedulable: false
        command: 'gsbcore:triggersynchronize'
        description: 'Used to trigger ExtensionConfiguration->synchronizeExtConfTemplateWithLocalConfigurationOfAllExtensions to get around readonly filesystem woes'


  ITZBund\GsbCore\Configuration\PackageHelper:
    public: true

  ITZBund\GsbCore\Configuration\ExtendSiteConfigurationRegistry:
    public: true

  ITZBund\GsbCore\Configuration\Discovery\ExtendSiteConfigurationLocator:
    public: true

  ITZBund\GsbCore\EventListener\AddInfoButtonToContentElementsEvent:
    public: true
    tags:
      - name: event.listener
        identifier: 'gsb_core/add-info-button-to-content-elements'

  ITZBund\GsbCore\EventListener\AddTypoScriptFromSitePackageEvent:
    public: true
    arguments:
      - '@ITZBund\GsbCore\Configuration\PackageHelper'
    tags:
      - name: event.listener
        identifier: 'gsb_core/add-typoscript-from-site-package'

  ITZBund\GsbCore\EventListener\ExtendsSiteConfigurationEvent:
    public: true
    tags:
      - name: event.listener
        identifier: 'gsb_core/extends-site-configuration'

  ITZBund\GsbCore\ViewHelpers\:
    resource: '../Classes/ViewHelpers/*'
    public: true

  ITZBund\GsbCore\Controller\ReportController:
    tags: ['backend.controller']
