base: 'https://docker-ddev-compose-gsbt3.pixelpark.docker/'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=52'
languages:
  -
    title: Deutsch
    enabled: true
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    websiteTitle: 'DPX Standardmandant'
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
    languageId: 0
    base: /
    solr_core_read: core_de
  -
    title: English
    enabled: true
    typo3Language: default
    locale: en_GB.UTF-8
    iso-639-1: en
    websiteTitle: 'DPX Standardmandant'
    navigationTitle: English
    hreflang: en-GB
    direction: ltr
    fallbackType: strict
    fallbacks: '0'
    flag: gb
    languageId: 1
    base: /en/
    solr_core_read: core_en
luxletterUnsubscribePid: /
rootPageId: 1
routes:
  -
    route: sitemap.xml
    type: uri
    source: 't3://page?uid=1&sitemap=pages&type=1533906435'
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\n"
solr_enabled_read: true
solr_host_read: solr
solr_path_read: /solr/
solr_port_read: '8983'
solr_scheme_read: http
solr_use_write_connection: false
websiteTitle: 'DPX Standardmandant'
